# Generated by Django 3.1 on 2020-09-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('k', models.IntegerField()),
                ('m', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
