# Generated by Django 3.1 on 2020-09-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20200903_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchpoint',
            name='m',
        ),
        migrations.AlterField(
            model_name='searchpoint',
            name='k',
            field=models.PositiveIntegerField(),
        ),
    ]
