# Generated by Django 3.1 on 2020-09-04 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20200904_1907'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchPoint',
        ),
    ]
