# Generated by Django 3.1.7 on 2021-03-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_delete_searchpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
