# Generated by Django 3.1.7 on 2021-03-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20210314_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='title',
        ),
        migrations.AddField(
            model_name='notes',
            name='title_1',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
