# Generated by Django 3.1.7 on 2021-03-14 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20210314_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='title_1',
            new_name='title',
        ),
    ]
