# Generated by Django 3.1.7 on 2021-03-14 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_auto_20210314_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='title',
            new_name='title_1',
        ),
    ]
